# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hashfunc <- function(key, randomint) {
    .Call('zobrist_hashfunc', PACKAGE = 'zobrist', key, randomint)
}

hashfunc_vec_cpp <- function(keys, randomint) {
    .Call('zobrist_hashfunc_vec_cpp', PACKAGE = 'zobrist', keys, randomint)
}

LocateKey <- function(key, keysize, randomint, hashtable) {
    .Call('zobrist_LocateKey', PACKAGE = 'zobrist', key, keysize, randomint, hashtable)
}

LocateKeys <- function(keys, keysize, randomint, hashtable) {
    .Call('zobrist_LocateKeys', PACKAGE = 'zobrist', keys, keysize, randomint, hashtable)
}

GetValueByKey <- function(key, keysize, randomint, hashtable) {
    .Call('zobrist_GetValueByKey', PACKAGE = 'zobrist', key, keysize, randomint, hashtable)
}

GetValueByKeys <- function(keys, keysize, randomint, hashtable) {
    .Call('zobrist_GetValueByKeys', PACKAGE = 'zobrist', keys, keysize, randomint, hashtable)
}

FindKey <- function(key, keysize, randomint, hashtable) {
    .Call('zobrist_FindKey', PACKAGE = 'zobrist', key, keysize, randomint, hashtable)
}

FindKeys <- function(keys, keysize, randomint, hashtable) {
    .Call('zobrist_FindKeys', PACKAGE = 'zobrist', keys, keysize, randomint, hashtable)
}

KeyToStr <- function(x, keysize) {
    .Call('zobrist_KeyToStr', PACKAGE = 'zobrist', x, keysize)
}

StrToKey <- function(x, keysize) {
    .Call('zobrist_StrToKey', PACKAGE = 'zobrist', x, keysize)
}

KeysToStrs <- function(x, keysize) {
    .Call('zobrist_KeysToStrs', PACKAGE = 'zobrist', x, keysize)
}

StrsToKeys <- function(x, keysize) {
    .Call('zobrist_StrsToKeys', PACKAGE = 'zobrist', x, keysize)
}

MakeHashTable <- function(htsize, values, index) {
    .Call('zobrist_MakeHashTable', PACKAGE = 'zobrist', htsize, values, index)
}

