# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hashfunc_vec_cpp <- function(keys, randomint) {
    .Call('zobrist_hashfunc_vec_cpp', PACKAGE = 'zobrist', keys, randomint)
}

